### ISSUE TITLE
refactor instantiable functions' names

### ISSUE THREAD

**Issue by uber5001** [Awk34/dotsynth#3]
We have "dot" and "connection". They should be "Dot" and "Connection". Class-like functions should use upper camel case; normal functions should use lower camel case. Not sure if there are more like this.

**Comment by Awk34** [comment]
dot -> Dot
connection -> Connection

**Comment by uber5001** [comment]
I think we still need to capitalize arc.

**Comment by Awk34** [comment]
_ahem_
done
